package composegen

import (
	"strings"
	"testing"
)

// containsAll fails the test for any wanted substring missing from s.
func containsAll(t *testing.T, s string, wants ...string) {
	t.Helper()
	for _, w := range wants {
		if !strings.Contains(s, w) {
			t.Errorf("output missing %q\n--- output ---\n%s", w, s)
		}
	}
}

// TestInstanceComposeContainsCoreElements asserts the generated single-instance
// compose carries the service, image, port, named volumes, the password
// placeholder, restart policy, and a healthcheck.
func TestInstanceComposeContainsCoreElements(t *testing.T) {
	out := InstanceCompose(InstanceComposeInput{
		Name:      "shop",
		PGVersion: "16",
		Image:     "pgfleet/postgres-pgbackrest:16",
		Port:      5432,
		RepoType:  "local",
		Superuser: "postgres",
	})

	containsAll(t, out,
		"# Generated by PgFleet",
		"shop",          // instance name in header
		"pg version 16", // header mentions version
		"services:",
		"pgfleet-pg-shop:", // service named like the container
		"image: pgfleet/postgres-pgbackrest:16",
		`"5432:5432"`,             // host->container port mapping
		"${POSTGRES_PASSWORD}",    // placeholder, never the real password
		"# set POSTGRES_PASSWORD", // env-file hint
		"restart: unless-stopped",
		"pg_isready", // healthcheck
		"healthcheck:",
		"volumes:",
		"pgfleet-data-shop:", // named data volume
		"pgfleet-repo-shop:", // named backup repo volume (local repo)
	)
}

// TestInstanceComposeNeverEmitsRealPassword guards the core security property:
// even if a password were available, the YAML must only ever reference the
// ${POSTGRES_PASSWORD} placeholder.
func TestInstanceComposeNeverEmitsRealPassword(t *testing.T) {
	out := InstanceCompose(InstanceComposeInput{
		Name:      "shop",
		PGVersion: "16",
		Image:     "pgfleet/postgres-pgbackrest:16",
		Port:      5432,
		RepoType:  "local",
		Superuser: "postgres",
	})
	if strings.Contains(out, "POSTGRES_PASSWORD: ") &&
		!strings.Contains(out, "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}") {
		t.Fatalf("password env is not a placeholder:\n%s", out)
	}
}

// TestInstanceComposeS3RepoHasNoRepoVolume verifies an S3-backed instance does
// not declare a local backup-repo volume (there is no local repo to mount).
func TestInstanceComposeS3RepoHasNoRepoVolume(t *testing.T) {
	out := InstanceCompose(InstanceComposeInput{
		Name:      "ware",
		PGVersion: "17",
		Image:     "pgfleet/postgres-pgbackrest:17",
		Port:      5432,
		RepoType:  "s3",
		Superuser: "postgres",
	})
	containsAll(t, out, "pgfleet-data-ware:")
	if strings.Contains(out, "pgfleet-repo-ware") {
		t.Fatalf("s3 instance should not declare a local repo volume:\n%s", out)
	}
}

// TestClusterComposeContainsMembersAndRouter asserts a cluster compose has the
// primary, every replica, and the PgCat router service with its 6432 port, plus
// depends_on wiring and the named volumes block.
func TestClusterComposeContainsMembersAndRouter(t *testing.T) {
	out := ClusterCompose(ClusterComposeInput{
		Name:        "hac",
		PrimaryName: "hac-p",
		PGVersion:   "16",
		Image:       "pgfleet/postgres-pgbackrest:16",
		Port:        5432,
		RepoType:    "local",
		Superuser:   "postgres",
		Replicas:    []string{"hac-r1", "hac-r2"},
		PgCatImage:  "ghcr.io/postgresml/pgcat:latest",
		RouterPort:  6432,
	})

	containsAll(t, out,
		"# Generated by PgFleet",
		"services:",
		"pgfleet-pg-hac-p:",   // primary service
		"pgfleet-pg-hac-r1:",  // replica 1
		"pgfleet-pg-hac-r2:",  // replica 2
		"pgfleet-router-hac:", // router service
		"image: ghcr.io/postgresml/pgcat:latest",
		`"6432:6432"`,      // router port
		"depends_on:",      // replicas depend on primary
		"pgfleet-pg-hac-p", // referenced as a dependency
		"${POSTGRES_PASSWORD}",
		"pgcat.toml", // comment that the router needs its config
		"volumes:",
		"pgfleet-data-hac-p:",  // primary data volume
		"pgfleet-data-hac-r1:", // replica data volume
	)
}

// TestClusterComposeNoReplicas keeps a primary+router cluster valid with zero
// replicas (no depends_on stanza is required, but the router must still front
// the primary).
func TestClusterComposeNoReplicas(t *testing.T) {
	out := ClusterCompose(ClusterComposeInput{
		Name:        "solo",
		PrimaryName: "solo-p",
		PGVersion:   "16",
		Image:       "pgfleet/postgres-pgbackrest:16",
		Port:        5432,
		RepoType:    "local",
		Superuser:   "postgres",
		Replicas:    nil,
		PgCatImage:  "ghcr.io/postgresml/pgcat:latest",
		RouterPort:  6432,
	})
	containsAll(t, out, "pgfleet-pg-solo-p:", "pgfleet-router-solo:")
}
